name: Process Font

on:
  workflow_dispatch:
    inputs:
      fontBase64:
        description: 'Base64 encoded font'
        required: true
      fileName:
        description: 'Font file name'
        required: true
        default: 'font.ttf'
      keepHinting:
        description: 'Keep hinting'
        required: false
        default: 'false'
      ignoreErrors:
        description: 'Ignore errors'
        required: false
        default: 'true'
      keepVars:
        description: 'Keep variable font features'
        required: false
        default: 'false'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fonttools
          pip install skia-pathops
          
      - name: Save